### ISSUE TITLE
Replace seawater with GSW

### ISSUE THREAD

**Issue by bhlevca** [hugocruzz/PyLake#3]
Sewawater was deprecated please replace seawater with GSW. I replaced it in all my code,

When using pylake I getting this warning:
`pylake.py:3: UserWarning: The seawater library is deprecated! Please use gsw instead.`

**Comment by f-baerenbold** [comment]
Hello

I was trying gsw instead and get an error: AttributeError: module 'gsw' has no attribute 'cp'

Also, I am not getting the warning for seawater (using python 3.9). But thanks for posting, we will look into this at a later stage.

**Comment by bhlevca** [comment]
I am using Python version 3.12.  However, I think that seawater itself is issuing the deprecating warning as the Python distribution does not know about its libraries. 

The repository at https://github.com/eawag-surface-waters-research/PyLake does not seem to accept Issues.  Which one should I follow?

**Comment by f-baerenbold** [comment]
I enabled the issues. Please write it there and I will look into it at some point.

**Comment by bhlevca** [comment]
Done
